# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Mustafa/Desktop/carGuess.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 570)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cBox_CarBrand = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_CarBrand.setGeometry(QtCore.QRect(50, 180, 111, 21))
        self.cBox_CarBrand.setObjectName("cBox_CarBrand")
        self.CarBrand_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarBrand_lbl.setGeometry(QtCore.QRect(50, 150, 91, 21))
        self.CarBrand_lbl.setObjectName("CarBrand_lbl")
        self.cBox_CarModel = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_CarModel.setGeometry(QtCore.QRect(230, 180, 111, 21))
        self.cBox_CarModel.setObjectName("cBox_CarModel")
        self.CarModel_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarModel_lbl.setGeometry(QtCore.QRect(230, 150, 91, 21))
        self.CarModel_lbl.setObjectName("CarModel_lbl")
        self.CarMileage_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarMileage_lbl.setGeometry(QtCore.QRect(380, 150, 91, 21))
        self.CarMileage_lbl.setObjectName("CarMileage_lbl")
        self.cbx_FuelType = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_FuelType.setGeometry(QtCore.QRect(710, 180, 111, 21))
        self.cbx_FuelType.setObjectName("cbx_FuelType")
        self.CarFuelType_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarFuelType_lbl.setGeometry(QtCore.QRect(710, 150, 111, 21))
        self.CarFuelType_lbl.setObjectName("CarFuelType_lbl")
        self.CarTax_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarTax_lbl.setGeometry(QtCore.QRect(390, 250, 91, 21))
        self.CarTax_lbl.setObjectName("CarTax_lbl")
        self.CarMPG_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarMPG_lbl.setGeometry(QtCore.QRect(540, 250, 91, 21))
        self.CarMPG_lbl.setObjectName("CarMPG_lbl")
        self.calculator_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calculator_btn.setGeometry(QtCore.QRect(690, 330, 141, 28))
        self.calculator_btn.setCheckable(False)
        self.calculator_btn.setObjectName("calculator_btn")
        self.CarGuessPrice_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarGuessPrice_lbl.setGeometry(QtCore.QRect(710, 370, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.CarGuessPrice_lbl.setFont(font)
        self.CarGuessPrice_lbl.setObjectName("CarGuessPrice_lbl")
        self.CarEngineSize_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarEngineSize_lbl.setGeometry(QtCore.QRect(540, 150, 91, 21))
        self.CarEngineSize_lbl.setObjectName("CarEngineSize_lbl")
        self.sBox_Mileage = QtWidgets.QSpinBox(self.centralwidget)
        self.sBox_Mileage.setGeometry(QtCore.QRect(370, 180, 111, 21))
        self.sBox_Mileage.setMaximum(999999)
        self.sBox_Mileage.setObjectName("sBox_Mileage")
        self.sBox_Tax = QtWidgets.QSpinBox(self.centralwidget)
        self.sBox_Tax.setGeometry(QtCore.QRect(390, 280, 111, 22))
        self.sBox_Tax.setMaximum(300)
        self.sBox_Tax.setObjectName("sBox_Tax")
        self.dSBox_MPG = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dSBox_MPG.setGeometry(QtCore.QRect(540, 280, 101, 22))
        self.dSBox_MPG.setMaximum(200.99)
        self.dSBox_MPG.setSingleStep(0.1)
        self.dSBox_MPG.setObjectName("dSBox_MPG")
        self.dSBox_EngineSize = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dSBox_EngineSize.setGeometry(QtCore.QRect(540, 180, 101, 22))
        self.dSBox_EngineSize.setMaximum(10.0)
        self.dSBox_EngineSize.setObjectName("dSBox_EngineSize")
        self.cBox_ChooseCompany = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_ChooseCompany.setGeometry(QtCore.QRect(680, 280, 141, 21))
        self.cBox_ChooseCompany.setObjectName("cBox_ChooseCompany")
        self.ChooseCompany_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ChooseCompany_lbl.setGeometry(QtCore.QRect(680, 250, 151, 21))
        self.ChooseCompany_lbl.setObjectName("ChooseCompany_lbl")
        self.CarYear_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarYear_lbl.setGeometry(QtCore.QRect(50, 240, 91, 21))
        self.CarYear_lbl.setObjectName("CarYear_lbl")
        self.date_CarYear = QtWidgets.QDateEdit(self.centralwidget)
        self.date_CarYear.setGeometry(QtCore.QRect(50, 270, 110, 22))
        self.date_CarYear.setObjectName("date_CarYear")
        self.cBox_CarTransmission = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_CarTransmission.setGeometry(QtCore.QRect(210, 270, 111, 21))
        self.cBox_CarTransmission.setObjectName("cBox_CarTransmission")
        self.CarTransmission_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CarTransmission_lbl.setGeometry(QtCore.QRect(210, 240, 111, 21))
        self.CarTransmission_lbl.setObjectName("CarTransmission_lbl")
        self.info_lbl = QtWidgets.QLabel(self.centralwidget)
        self.info_lbl.setGeometry(QtCore.QRect(130, 80, 511, 16))
        self.info_lbl.setText("")
        self.info_lbl.setObjectName("info_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CarBrand_lbl.setText(_translate("MainWindow", "Car Brand"))
        self.CarModel_lbl.setText(_translate("MainWindow", "Car Model"))
        self.CarMileage_lbl.setText(_translate("MainWindow", "Mileage"))
        self.CarFuelType_lbl.setText(_translate("MainWindow", "Car Fuel Type"))
        self.CarTax_lbl.setText(_translate("MainWindow", "Tax"))
        self.CarMPG_lbl.setText(_translate("MainWindow", "MPG"))
        self.calculator_btn.setText(_translate("MainWindow", "GUESS"))
        self.CarGuessPrice_lbl.setText(_translate("MainWindow", "99999 $"))
        self.CarEngineSize_lbl.setText(_translate("MainWindow", "Engine Size"))
        self.ChooseCompany_lbl.setText(_translate("MainWindow", "Choose a Company"))
        self.CarYear_lbl.setText(_translate("MainWindow", "Car Year"))
        self.date_CarYear.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.CarTransmission_lbl.setText(_translate("MainWindow", "Car Transmission"))

